kind: PersistentVolume
apiVersion: v1
metadata:
    name: blog-pv-volume
    labels:
        type: local
        app: blog-postgres
spec:
    storageClassName: microk8s-hostpath
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/opt/postgres/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: blog-pv-claim
    labels:
        app: blog-postgres
spec:
    storageClassName: microk8s-hostpath
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 5Gi
