apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "blog-ui-chart.fullname" . }}-config
    labels:
        {{- include "blog-ui-chart.labels" . | nindent 8 }}
data:
    API_ENV_NAME: {{ .Values.apiEnvName }}_PORT
