apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "blog-ui-chart.fullname" . }}-gateway
spec:
  selector:
    istio: {{ .Values.istio.selector }} # use istio default controller
  servers:
    - port:
        number: {{ .Values.service.port }}
        name: {{ include "blog-ui-chart.fullname" . }}-http
        protocol: HTTPS
      tls:
          mode: SIMPLE
          serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
          privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
        {{- range .Values.istio.hosts }}
        - {{ . | quote}}
        {{- end}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "blog-ui-chart.fullname" . }}-istio
spec:
  hosts:
    {{- range .Values.istio.hosts }}
    - {{ . | quote}}
    {{- end}}
  gateways:
    - {{ include "blog-ui-chart.fullname" . }}-gateway
  http:
  - match:
    {{- range .Values.istio.match }}
    - uri:
        exact: {{ .uri.exact }}
    {{- end}}
    route:
    - destination:
        host: {{ include "blog-ui-chart.fullname" . }}-service
        port:
          number: {{ .Values.service.port }}
