apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog-ui-chart.fullname" . }}-service
  labels:
    {{- include "blog-ui-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: {{ include "blog-ui-chart.fullname" . }}-http
  selector:
    {{- include "blog-ui-chart.selectorLabels" . | nindent 4 }}
